generate_kwargs:
  model: gpt-4o
  timeout: 60
  temperature: 0.3
  max_tokens: 3
  n : 1

num_samples: 20
random_state: 42

wandb_init:
  job_type: "generate-openai-answers"
  tags: ["openai", "answers", "${generate_kwargs.model}"]

version: "v2"

input_file_name: "openai-questions-${version}.parquet"
input_artifact:
  artifact_or_name: "openai-questions-${version}:latest"
  type: "openai-synthetic"


output_file_name: "openai-answers-${version}.parquet"
output_artifact:
  name: "openai-answers-${version}"
  type: "openai-synthetic"
  metadata: 
    model_name: ${generate_kwargs.model}