model_entity: nomic-ai
model_name: nomic-embed-text-v1
model_name_or_path: ${model_entity}/${model_name}
output_dir: ../checkpoints/rag/${model_name}

wandb_init:
  job_type: "add-options-rag"
  tags: ["${model_name}", "replay-RAG"]


input_artifact_version: "v2"
file_name_knowledge: "openai-knowledge-${input_artifact_version}.parquet"
input_artifact_knowledge:
  artifact_or_name: "openai-knowledge-${input_artifact_version}:latest"
  type: "openai-synthetic"

task : "guess"

file_name_games: "${task}.parquet"
input_artifact_games:
  artifact_or_name: "replay-dataframe-${task}:latest"
  type: "replay-games"

output_file_name: "${task}.parquet"
output_artifact:
  name: "replay-rag-${model_name}"
  type: replay-rag
  metadata: 
    model_name: ${model_name}
