model_org: solidrust
model_name: Meta-Llama-3-8B-Instruct-hf-AWQ
task: guess
output_dir: ../checkpoints/${model_name}/${task}

model: 
  pretrained_model_name_or_path: ${model_org}/${model_name}
  torch_dtype: ${dtype:fp16}
  attn_implementation: flash_attention_2


trainer:
  output_dir: ${output_dir}
  overwrite_output_dir: True
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 2
  learning_rate: 2e-4
  save_strategy: steps
  num_train_epochs: 1
  logging_steps: 5
  save_steps: 20
  save_total_limit: 2
  eval_strategy: steps
  eval_steps: 20
  eval_accumulation_steps: 1
  fp16_full_eval: True
  load_best_model_at_end: True
  max_steps: -1
  dataloader_num_workers: 4
  dataloader_persistent_workers: True
  report_to: wandb
  fp16: True
  optim: 'paged_adamw_8bit'
  group_by_length: True
  length_column_name: 'input_length'
  ddp_find_unused_parameters: False

lora:
    r: 16
    lora_alpha: 16
    lora_dropout: 0.1
    target_modules: ['up_proj', 'down_proj', 'gate_proj', 'k_proj', 'q_proj', 'v_proj', 'o_proj']
    bias: "none"
    task_type: "CAUSAL_LM"
